extract_clauses_task:
  description: >
    Thoroughly read the provided {legal_document} and extract all important clauses.
    Focus on Termination, Payment Terms, Confidentiality, Indemnity, and Liability.
  expected_output: >
    A clearly structured list of clauses, each with a title and full clause text.
  agent: clause_extractor

detect_risks_task:
  description: >
    Analyze the extracted clauses from the {legal_document}.
    Identify any missing protections, ambiguous language, or hidden liabilities.
  expected_output: >
    A detailed risk report, listing each risk found along with a short explanation.
  agent: risk_detector

summarize_document_task:
  description: >
    Summarize the {legal_document} into an executive-friendly overview.
    Highlight main obligations, deadlines, risks, and critical terms.
  expected_output: >
    A 5-paragraph plain English summary that simplifies the document while keeping key details.
  agent: summarizer
