# extract_clauses_task:
#   description: >
#     Extract all important clauses from the provided legal document. 
#     Focus on termination, confidentiality, payment, and liability clauses.
#   expected_output: >
#     A structured list of clauses, with clause titles and their corresponding full text.

# detect_risks_task:
#   description: >
#     Analyze the extracted clauses and detect potential legal risks, ambiguities, 
#     or missing protections. Highlight any sections that could cause future disputes.
#   expected_output: >
#     A detailed risk report listing each identified risk with a short explanation.

# summarize_document_task:
#   description: >
#     Summarize the entire legal document focusing on key obligations, risks, and important deadlines.
#   expected_output: >
#     A 5-paragraph executive summary written in plain English.


# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst


# extract_clauses_task:
#   description: >
#     Thoroughly read the provided {legal_document} and extract all important clauses.
#     Focus on Termination, Payment Terms, Confidentiality, Indemnity, and Liability.
#   expected_output: >
#     A clearly structured list of clauses, each with a title and full clause text.
#   agent: clause_extractor

# detect_risks_task:
#   description: >
#     Analyze the extracted clauses from the {legal_document}.
#     Identify any missing protections, ambiguous language, or hidden liabilities.
#   expected_output: >
#     A detailed risk report, listing each risk found along with a short explanation.
#   agent: risk_detector

# summarize_document_task:
#   description: >
#     Summarize the {legal_document} into an executive-friendly overview.
#     Highlight main obligations, deadlines, risks, and critical terms.
#   expected_output: >
#     A 5-paragraph plain English summary that simplifies the document while keeping key details.
#   agent: summarizer



extract_clauses_task:
  description: >
    Thoroughly read the provided {legal_document} and extract all important clauses.
    Focus on Termination, Payment Terms, Confidentiality, Indemnity, and Liability.
  expected_output: >
    A clearly structured list of clauses, each with a title and full clause text.
  agent: clause_extractor

detect_risks_task:
  description: >
    Analyze the extracted clauses from the {legal_document}.
    Identify any missing protections, ambiguous language, or hidden liabilities.
  expected_output: >
    A detailed risk report, listing each risk found along with a short explanation.
  agent: risk_detector

summarize_document_task:
  description: >
    Summarize the {legal_document} into an executive-friendly overview.
    Highlight main obligations, deadlines, risks, and critical terms.
  expected_output: >
    A 5-paragraph plain English summary that simplifies the document while keeping key details.
  agent: summarizer
